name: e2e-test-trigger.yml
on:
  workflow_run:
    workflows: [ "Deploy Angular to EC2" ]
    types:
      - completed

jobs:
  e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ vars.BASE_URL }}
      ROUTES: ${{ vars.ROUTES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test main-ally.spec.ts

      - name: Rename report folder
        if: always()
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          mv playwright-report "playwright-report-$TIMESTAMP"
          echo "REPORT_FOLDER=playwright-report-$TIMESTAMP" >> $GITHUB_ENV

      - name: Upload accessibility report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPORT_FOLDER }}
          path: ${{ env.REPORT_FOLDER }}
